apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{namespace}}'
  name: '{{deployment_name}}'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: '{{app_name}}'
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{app_name}}'
    spec:
      containers:
      - image: '{{image_name}}'
        imagePullPolicy: Always
        name: '{{app_name}}'
        env:
        - name: PORT
          value: "80" 
        resources:
           limits:
             memory: "128Mi"
             cpu: "300m"
           requests:
             memory: "64Mi"
             cpu: "200m"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
              path: /liveness
              port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 24
          timeoutSeconds: 1
