apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: '{{namespace}}'
  name: '{{ingress_name}}'
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: '{{service_name}}'
              port:
                number: 80