apiVersion: v1
kind: Service
metadata:
  namespace: '{{namespace}}'
  name: '{{service_name}}'
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: '{{app_name}}'